### ISSUE TITLE
node js V  0.10.24报错

### ISSUE THREAD

**Issue by TChenQuan** [moyuyc/request-song-robot#1]
```
[root@www static]# song-robot -p 9888

/usr/local/node/0.10.24/lib/node_modules/song-robot/src/server/index.js:27
app.listen(argv.p || 9888, () => {
                            ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

**Comment by moyuyc** [comment]
node坂本需要6以上

**Comment by TChenQuan** [comment]
方便留个联系方式么

**Comment by TChenQuan** [comment]
http://150.129.83.24:9888/   多个报错

**Comment by TChenQuan** [comment]
```
/
/style.css
/core.js
/favicon.ico
/api/sug?s=n
/api/sug?s=ni
/api/sug?s=ni%27h
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=ni%27ha
/api/sug?s=ni%27hao
/api/sug?s=ni
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=n
/api/sug?s=ni%27h
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=%E4%BD%A0%E5%A5%BD
/api/sug?s=ni
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=ni%27ha
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=ni%27hao
/api/sug?s=ni%27h
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=%E4%BD%A0%E5%A5%BD
/api/sug?s=ni%27ha
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=ni%27hao
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=%E4%BD%A0%E5%A5%BD
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
(node:5281) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'code' of undefined
/api/sug?s=B
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9B
/api/sug?s=B%EF%BC%9Ba
/api/sug?s=B%EF%BC%9Ban
/api/sug?s=B%EF%BC%9Ba%27na
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Banak
/api/sug?s=B%EF%BC%9B
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Banak
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Ban
/api/sug?s=B%EF%BC%9B
/api/sug?s=B%EF%BC%9Ba%27na
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Banak
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Ban
/api/sug?s=B%EF%BC%9B
/api/sug?s=B%EF%BC%9Ba%27na
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Ba
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Ban
/api/sug?s=B%EF%BC%9Ba
/api/sug?s=B%EF%BC%9Ba%27na
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Ban
/api/sug?s=B%EF%BC%9Ba%27na
/api/sug?s=B%EF%BC%9Ba
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Ban
/api/sug?s=B%EF%BC%9Ba
/api/sug?s=Bl
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=B%EF%BC%9Ba%27na
/api/sug?s=Bla
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=Blan
/api/sug?s=Blank
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=Blanks
/api/sug?s=Blanksp
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=Blankspa
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=Blankspac
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=Blankspace
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=Blank%20space
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
(node:5281) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'code' of undefined
/
/style.css
/core.js
/favicon.ico
/api/sug?s=l
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=li
/api/sug?s=l
/api/sug?s=li%27b
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=li%27ba
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=li
/api/sug?s=li%27bai
/api/sug?s=li%27bai
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=li
/api/sug?s=li%27b
/api/sug?s=li%27ba
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=li%27bai
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=%E6%9D%8E%E7%99%BD
/api/sug?s=%E6%9D%8E%E7%99%BD
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=li%27b
/api/sug?s=li%27ba
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
(node:5281) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'code' of undefined
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=%E6%9D%8E%E7%99%BD
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/
/core.js
/style.css
/favicon.ico
/api/sug?s=1
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=1
/api/sug?s=12
/api/sug?s=12
/api/sug?s=12
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=123
/api/sug?s=1
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=123
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/api/sug?s=123
TypeError: Cannot read property 'map' of undefined
    at util.spider.then.json (/usr/local/node/0.10.24/lib/node_modules/song-robot/src/getsong/index.js:24:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/style.css

```

**Comment by moyuyc** [comment]
你加我qq  492899414吧
